name: Limit Repo Interactions

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  limitInteractions:
    runs-on: ubuntu-latest
    steps:
      - name: Set repository interaction limits
        run: |
          curl --request PUT \
          --url https://api.github.com/repos/${{ github.repository }}/interaction-limits \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'accept: application/vnd.github.sombra-preview' \
          --data '{
          "limit": "existing_users",
          }'
